{{- if .Values.rbac.create }}
{{- if .Values.secretsExporter.enabled }}
---
apiVersion: {{ include "capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "x509-certificate-exporter.secretsExporterClusterRoleName" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
  {{- with .Values.rbac.secretsExporter.clusterRoleAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
{{- if .Values.rbacProxy.enable }}
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}
{{- if .Values.psp.create }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ include "x509-certificate-exporter.secretsExporterName" . }}
{{- end }}
{{- end }}
{{- if .Values.hostPathsExporter.daemonSets }}
---
apiVersion: {{ include "capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "x509-certificate-exporter.hostPathsExporterClusterRoleName" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
  {{- with .Values.rbac.hostPathsExporter.clusterRoleAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- if .Values.rbacProxy.enable }}
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}
{{- if .Values.psp.create }}
{{- with .Values.hostPathsExporter.daemonSets }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  {{- range $dsName, $dsDef := . }}
  - {{ printf "%s-%s" (include "x509-certificate-exporter.fullname" $) $dsName }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
