{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "x509-certificate-exporter.fullname" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.service.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
{{- with .Values.service.annotations }}
  annotations:
    {{- . | toYaml | trim | nindent 4 }}
{{- end }}
spec:
  {{- if not .Values.service.nodePort }}
  clusterIP: None
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: metrics
    {{- with .Values.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    {{- include "x509-certificate-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
