{{- if .Values.prometheusServiceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "x509-exporter.fullname" . }}
  labels:
    {{- include "x509-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.prometheusServiceMonitor.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "x509-exporter.selectorLabels" . | nindent 6 }}
  jobLabel: app.kubernetes.io/name
  endpoints:
  - port: metrics
    interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
  {{- if .Values.rbacProxy.enable }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  {{- end }}
  {{- with .Values.prometheusServiceMonitor.relabelings }}
    relabelings:
      {{ . | toYaml | indent 6 }}
  {{- end }}
{{- end }}
