# Copyright (c) 2021 Enix, SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing
# permissions and limitations under the License.
#
# Authors:
# Paul Laffitte <paul.laffitte@enix.fr>
# Alexandre Buisine <alexandre.buisine@enix.fr>

# Default values for san-iscsi-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Path to kubelet
kubeletPath: /var/lib/kubelet
# -- Wether psp admission controller has been enabled in the cluster or not
pspAdmissionControllerEnabled: false

image:
  # -- Docker repository to use for nodes and controller
  repository: docker.io/enix/san-iscsi-csi
  # -- Tag to use for nodes and controller
  # @default -- The chart will use the appVersion value by default if not given.
  tag: ""

# -- Controller sidecar for provisionning
csiProvisioner:
  image:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    tag: v2.1.0
  # -- Timeout for gRPC calls from the csi-provisioner to the controller
  timeout: 30s
  # -- Extra arguments for csi-provisioner controller sidecar
  extraArgs: []

# -- Controller sidecar for attachment handling
csiAttacher:
  image:
    repository: k8s.gcr.io/sig-storage/csi-attacher
    tag: v2.2.1
  # -- Timeout for gRPC calls from the csi-attacher to the controller
  timeout: 30s
  # -- Extra arguments for csi-attacher controller sidecar
  extraArgs: []

# -- Controller sidecar for volume expansion
csiResizer:
  image:
    repository: k8s.gcr.io/sig-storage/csi-resizer
    tag: v1.1.0
  # -- Extra arguments for csi-resizer controller sidecar
  extraArgs: []

# -- Controller sidecar for snapshots handling
csiSnapshotter:
  image:
    repository: k8s.gcr.io/sig-storage/csi-snapshotter
    tag: v4.0.0
  # -- Extra arguments for csi-snapshotter controller sidecar
  extraArgs: []

# -- Node sidecar for plugin registration
csiNodeRegistrar:
  image:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: v2.1.0
  # -- Extra arguments for csi-node-registrar node sidecar
  extraArgs: []

controller:
  # -- Extra arguments for san-iscsi-csi-controller container
  extraArgs: []

node:
  # -- Extra arguments for san-iscsi-csi-node containers
  extraArgs: []

# -- Container that convert CSI liveness probe to kubernetes liveness/readiness probe
nodeLivenessProbe:
  image:
    repository: quay.io/k8scsi/livenessprobe
    tag: v2.2.0
  # -- Extra arguments for the node's liveness probe containers
  extraArgs: []

nodeServer:
  # -- Kubernetes nodeSelector field for san-iscsi-csi-node-server Pod
  nodeSelector:
  # -- Kubernetes nodeAffinity field for san-iscsi-csi-node-server Pod
  nodeAffinity:

podMonitor:
  # -- Set a Prometheus operator PodMonitor ressource (true or false)
  enabled: false

serviceMonitor:
  # -- Set a Prometheus operator ServiceMonitor ressource (true or false)
  enabled: false
