kind: ClusterRoleBinding
apiVersion: {{ include "capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ include "kube-router.fullname" . }}
  labels:
    {{- include "kube-router.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-router.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-router.fullname" . }}
  namespace: {{ .Release.Namespace }}