apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kube-router.fullname" . }}
  labels:
    {{- include "kube-router.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-router.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "kube-router.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      priorityClassName: system-node-critical
      serviceAccountName: {{ include "kube-router.fullname" . }}
      containers:
      - name: kube-router
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if not (kindIs "invalid" .Values.kubeRouter.apiServerUrl) }}
        - "--master={{ .Values.kubeRouter.apiServerUrl }}"
        {{- end }}
        {{- if not (kindIs "invalid" .Values.kubeRouter.enablePprof) }}
        - "--enable-pprof={{ .Values.kubeRouter.enablePprof }}"
        {{- end }}
        {{- if not (kindIs "invalid" .Values.kubeRouter.cacheSyncTimeout) }}
        - "--cache-sync-timeout={{ .Values.kubeRouter.cacheSyncTimeout }}"
        {{- end }}
        {{- if not (kindIs "invalid" .Values.kubeRouter.healthPort) }}
        - "--health-port={{ .Values.kubeRouter.healthPort }}"
        {{- end }}
        {{- if not (kindIs "invalid" .Values.kubeRouter.metrics.path) }}
        - "--metrics-path={{ .Values.kubeRouter.metrics.path }}"
        {{- end }}
        {{- if not (kindIs "invalid" .Values.kubeRouter.metrics.port) }}
        - "--metrics-port={{ .Values.kubeRouter.metrics.port }}"
        {{- end }}
        {{- with .Values.kubeRouter.router }}
        {{- if .enabled }}
        - "--run-router=true"
        {{- if not (kindIs "invalid" .bgpRouterId) }}
        - "--router-id={{ .bgpRouterId }}"
        {{- end }}
        {{- if .peers }}
        - "--peer-router-ips=
          {{- range $i, $peer := .peers }}
          {{- if not (eq $i 0) }},{{ end }}
          {{- required ( print "Missing IP address for BGP peer in kubeRouter.router.peers[" $i "]" ) ( default "" $peer.ip | trim ) }}
          {{- end }}"
        - "--peer-router-asns=
          {{- range $i, $peer := .peers }}
          {{- if not (eq $i 0) }},{{ end }}
          {{- required ( print "Missing or invalid AS number for BGP peer in kubeRouter.router.peers[" $i "]" ) ( regexFind "^[0-9]+$" ( $peer.asn | toString )) }}
          {{- end }}"
        {{- $passwords := list -}}
        {{- $pw_count := 0 -}}
        {{- range $i, $peer := .peers -}}
        {{- if $peer.password -}}
        {{- if regexMatch "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$" ( $peer.password | trim ) -}}
        {{- $passwords = append $passwords ( $peer.password | trim ) -}}
        {{- $pw_count = add1 $pw_count -}}
        {{- else -}}
        {{- fail ( print "Invalid Base64 string for password of BGP peer in kubeRouter.router.peers[" $i "]" ) -}}
        {{- end -}}
        {{- else -}}
        {{- $passwords = append $passwords "" -}}
        {{- end -}}
        {{- end -}}
        {{- if gt $pw_count 0 }}
        - "--peer-router-passwords={{ join "," $passwords }}"
        {{- end }}
        {{- $ports := list -}}
        {{- $pt_count := 0 -}}
        {{- range $i, $peer := .peers -}}
        {{- if $peer.port -}}
        {{- if and ( regexMatch "^[0-9]+$" ( $peer.port | toString )) ( gt ( $peer.port | int ) 0 ) ( lt ( $peer.port | int ) 65536 ) -}}
        {{- $ports = append $ports ( $peer.port | toString | trim ) -}}
        {{- $pt_count = add1 $pt_count -}}
        {{- else -}}
        {{- fail ( print "Invalid port number for BGP peer in kubeRouter.router.peers[" $i "]" ) -}}
        {{- end -}}
        {{- else -}}
        {{- $ports = append $ports "179" -}}
        {{- end -}}
        {{- end -}}
        {{- if gt $pt_count 0 }}
        - "--peer-router-ports={{ join "," $ports }}"
        {{- end }}
        {{- end }}
        {{- if not (kindIs "invalid" .peerRouterMultihopTtl) }}
        - "--peer-router-multihop-ttl={{ .peerRouterMultihopTtl }}"
        {{- end }}
        {{- if not (kindIs "invalid" .overrideNexthop) }}
        - "--override-nexthop={{ .overrideNexthop }}"
        {{- end }}
        {{- if not (kindIs "invalid" .overlayType) }}
        - "--overlay-type={{ .overlayType }}"
        {{- end }}
        {{- if not (kindIs "invalid" .nodesFullMesh) }}
        - "--nodes-full-mesh={{ .nodesFullMesh }}"
        {{- end }}
        {{- if not (kindIs "invalid" .enablePodEgress) }}
        - "--enable-pod-egress={{ .enablePodEgress }}"
        {{- end }}
        {{- if not (kindIs "invalid" .enableOverlay) }}
        - "--enable-overlay={{ .enableOverlay }}"
        {{- end }}
        {{- if not (kindIs "invalid" .enableIbgp) }}
        - "--enable-ibgp={{ .enableIbgp }}"
        {{- end }}
        {{- if not (kindIs "invalid" .enableCni) }}
        - "--enable-cni={{ .enableCni }}"
        {{- end }}
        {{- if not (kindIs "invalid" .disableSourceDestCheck) }}
        - "--disable-source-dest-check={{ .disableSourceDestCheck }}"
        {{- end }}
        {{- if not (kindIs "invalid" .clusterAsn) }}
        - "--cluster-asn={{ .clusterAsn }}"
        {{- end }}
        {{- if not (kindIs "invalid" .bgpPort) }}
        - "--bgp-port={{ .bgpPort }}"
        {{- end }}
        {{- if not (kindIs "invalid" .bgpGracefulRestartDeferralTime) }}
        - "--bgp-graceful-restart-deferral-time={{ .bgpGracefulRestartDeferralTime }}"
        {{- end }}
        {{- if not (kindIs "invalid" .bgpGracefulRestart) }}
        - "--bgp-graceful-restart={{ .bgpGracefulRestart }}"
        {{- end }}
        {{- if not (kindIs "invalid" .advertisePodCidr) }}
        - "--advertise-pod-cidr={{ .advertisePodCidr }}"
        {{- end }}
        {{- if not (kindIs "invalid" .advertiseLoadbalancerIp) }}
        - "--advertise-loadbalancer-ip={{ .advertiseLoadbalancerIp }}"
        {{- end }}
        {{- if not (kindIs "invalid" .advertiseExternalIp) }}
        - "--advertise-external-ip={{ .advertiseExternalIp }}"
        {{- end }}
        {{- if not (kindIs "invalid" .advertiseClusterIp) }}
        - "--advertise-cluster-ip={{ .advertiseClusterIp }}"
        {{- end }}
        {{- if not (kindIs "invalid" .routesSyncPeriod) }}
        - "--routes-sync-period={{ .routesSyncPeriod }}"
        {{- end }}
        {{- else}}
        - "--run-router=false"
        {{- end }}
        {{- end }}

        {{- with .Values.kubeRouter.firewall }}
        {{- if .enabled }}
        - "--run-firewall=true"
        {{- if not (kindIs "invalid" .iptablesSyncPeriod) }}
        - "--iptables-sync-period={{ .iptablesSyncPeriod }}"
        {{- end }}
        {{- else}}
        - "--run-firewall=false"
        {{- end }}
        {{- end }}

        {{- with .Values.kubeRouter.serviceProxy }}
        {{- if .enabled }}
        - "--run-service-proxy=true"
        {{- if not (kindIs "invalid" .nodeportBindonAllIp) }}
        - "--nodeport-bindon-all-ip={{ .nodeportBindonAllIp }}"
        {{- end }}
        {{- if not (kindIs "invalid" .masqueradeAll) }}
        - "--masquerade-all={{ .masqueradeAll }}"
        {{- end }}
        {{- if not (kindIs "invalid" .ipvsSyncPeriod) }}
        - "--ipvs-sync-period={{ .ipvsSyncPeriod }}"
        {{- end }}
        {{- if not (kindIs "invalid" .ipvsPermitAll) }}
        - "--ipvs-permit-all={{ .ipvsPermitAll }}"
        {{- end }}
        {{- if not (kindIs "invalid" .ipvsGracefulTermination) }}
        - "--ipvs-graceful-termination={{ .ipvsGracefulTermination }}"
        {{- end }}
        {{- if not (kindIs "invalid" .ipvsGracefulPeriod) }}
        - "--ipvs-graceful-period={{ .ipvsGracefulPeriod }}"
        {{- end }}
        {{- if not (kindIs "invalid" .hairpinMode) }}
        - "--hairpin-mode={{ .hairpinMode }}"
        {{- end }}
        {{- if not (kindIs "invalid" .excludedCidrs) }}
        - "--excluded-cidrs={{ .excludedCidrs }}"
        {{- end }}
        {{- if not (kindIs "invalid" .runtimeEndpoint) }}
        - "--runtime-endpoint={{ .runtimeEndpoint }}"
        {{- end }}
        {{- else}}
        - "--run-service-proxy=false"
        {{- end }}
        {{- end }}
        {{- range $item := .Values.kubeRouter.extraArgs }}
        - {{ $item|quote }}
        {{- end }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_ROUTER_CNI_CONF_FILE
          value: /etc/cni/net.d/10-kuberouter.conflist
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{ . | toYaml | indent 10 | trim }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{ . | toYaml | indent 10 | trim }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
        - name: xtables-lock
          mountPath: /run/xtables.lock
          readOnly: false
        {{- if not (kindIs "invalid" .Values.kubeRouter.metrics.port) }}
        ports:
        - containerPort: {{ .Values.kubeRouter.metrics.port }}
          name: metrics
          protocol: TCP
        {{- end }}
      initContainers:
      {{- if .Values.kubeRouter.cni.install }}
      - name: install-cni
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - set -e -x;
          download_url=$(eval echo $CNI_DOWNLOAD_URL);
          echo $download_url;
          current_version="/cni-bin/.version";
          if ! [ $(cat $current_version) = "$download_url" ]; then
            wget "$download_url" -O - | tar zxf - -C "/cni-bin/";
            echo -n $download_url > $current_version;
          fi;
        env:
        - name: CNI_DOWNLOAD_URL
          value: {{ .Values.kubeRouter.cni.downloadUrl }}
        - name: CNI_VERSION
          value: {{ .Values.kubeRouter.cni.version }}
        volumeMounts:
        - name: cni-bin-dir
          mountPath: /cni-bin
      {{- end }}
      {{- if or (kindIs "invalid" .Values.kubeRouter.router.enableCni) .Values.kubeRouter.router.enableCni }}
      - name: configure-cni
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - set -e -x;
          if [ ! -f /etc/cni/net.d/10-kuberouter.conflist ]; then
            if [ -f /etc/cni/net.d/*.conf ]; then
              rm -f /etc/cni/net.d/*.conf;
            fi;
            TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
            cp /etc/kube-router/cni-conf.json ${TMP};
            mv ${TMP} /etc/cni/net.d/10-kuberouter.conflist;
          fi;
        volumeMounts:
        - mountPath: /etc/cni/net.d
          name: cni-conf-dir
        - mountPath: /etc/kube-router
          name: kube-router-cfg
      {{- end }}
      hostNetwork: true
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: cni-conf-dir
        hostPath:
          path: /etc/cni/net.d
      - name: kube-router-cfg
        configMap:
          name: {{ include "kube-router.fullname" . }}-cfg
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      {{- if .Values.kubeRouter.cni.install }}
      - name: cni-bin-dir
        hostPath:
          path: {{ .Values.kubeRouter.cni.installPath }}
      {{- end }}
