# when bumping version, please:
# - replace the "changes" annotation with new content
# - update "containsSecurityUpdates" if needed
version: 1.13.0
# when bumping appVersion, please:
# - update the "images" annotation
appVersion: 2.9.1
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - "exporter: Base image update (fixes security scan warnings)"
    - "Add support for metric labels filtering (new in exporter v2.9.0)"
    - "Detect Kubernetes version and guess best apiVersion for Deployment and RBAC"
    - "Fix missing labels on Pods"
    - "Helm template refactoring and style changes"
  artifacthub.io/images: |
    - name: x509-certificate-exporter
      image: enix/x509-certificate-exporter:2.9.1
    - name: kube-rbac-proxy
      image: quay.io/coreos/kube-rbac-proxy:v0.5.0
      whitelisted: true
  artifacthub.io/links: |
    - name: Chart Sources
      url: https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
    - name: Application Sources
      url: https://github.com/enix/x509-certificate-exporter
    - name: Helm Repository
      url: https://charts.enix.io
    - name: Grafana Dashboard
      url: https://grafana.com/grafana/dashboards/13922
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

apiVersion: v2
name: x509-certificate-exporter
type: application
description: A Prometheus exporter for certificates focusing on expiration monitoring
keywords:
- prometheus
- exporter
- certificate
- expiration
home: https://github.com/enix/x509-certificate-exporter
icon: https://github.githubassets.com/images/icons/emoji/unicode/1f50f.png
sources:
- https://github.com/enix/x509-certificate-exporter
- https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
maintainers:
- name: Enix
  email: contact@enix.fr
  url: https://github.com/enixsas
- name: Thibault Vincent
  email: root@paraneko.org
  url: https://github.com/npdgm
- name: Arthur Chaloin
  email: arthur.chaloin@enix.fr
