apiVersion: v2
name: x509-certificate-exporter
version: 1.8.0
# when bumping appVersion, change the annotation too (manual for now)
appVersion: 2.6.1
type: application
description: A Prometheus exporter for certificates focusing on expiration monitoring
keywords:
- prometheus
- exporter
- certificate
- expiration
home: https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
icon: https://github.githubassets.com/images/icons/emoji/unicode/1f50f.png
sources:
- https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
- https://github.com/enix/x509-certificate-exporter
maintainers:
- name: Enix
  email: contact@enix.fr
  url: https://github.com/enixsas
- name: Thibault Vincent
  email: root@paraneko.org
  url: https://github.com/npdgm
- name: Arthur Chaloin
  email: arthur.chaloin@enix.fr
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: x509-certificate-exporter
      image: enix/x509-certificate-exporter:2.6.1
    - name: kube-rbac-proxy
      image: quay.io/coreos/kube-rbac-proxy:v0.5.0
      whitelisted: true
