name: Publish OCI charts

on:
  workflow_dispatch:
      inputs:
        index_path:
          description: 'OCI index.yaml path without registry prefix'
          required: true

env:
  REGISTRY: quay.io

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Setup Oras
        uses: oras-project/setup-oras@v1

      - name: Download index.yaml
        #uses: mikefarah/yq@master
        run: |
          mkdir dist/
          oras pull ${REGISTRY}/${{ inputs.index_path }} -o dist/
          cat dist/index.yaml

      - name: Merge index.yaml
        uses: mikefarah/yq@master
        with:
          run: |
            yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' index.yaml dist/index.yaml > merge.yaml
            cat merge.yaml
